### ISSUE TITLE
Question about computing the intercept

### ISSUE THREAD

**Issue by Aliciawyse** [ankane/eps#11]
Hi there!

I have the following code: 

`model = Eps::LinearRegression.new(x, y)`

It outputs something like

![image](https://user-images.githubusercontent.com/13841769/69347518-9aa37580-0c42-11ea-8675-7279dd5b2cb1.png)

I have a question about that text highlighted in pink. Is there a way to prevent the intercept from being calculated? 

For example, the [scikit learn library](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html) has this `fit_intercept` method that can be set to true to false, allowing me to say when I want an intercept to be used in calculations. 

Is this possible with this library?

**Comment by ankane** [comment]
Hey @Aliciawyse, added on master.

```ruby
Eps::LinearRegression.new(x, y, intercept: false)
```

**Comment by Aliciawyse** [comment]
wow, thanks!
