### ISSUE TITLE
bug in evaluator?

### ISSUE THREAD

**Issue by mikemanyoung** [ankane/eps#20]
I got this error when creating a model:

https://gist.github.com/mikemanyoung/b4fb5e9b21c1dea7c9639fbd3cc07ea7

**Comment by mikemanyoung** [comment]
Seems to only happen when I use a text feature. When I remove the text feature, seems to go away.

**Comment by ankane** [comment]
Hey @mikemanyoung, I can help debug if you can put together a reproducible example you're able to share (feel free to send me an email if you'd prefer not to post the dataset here).

**Comment by mikemanyoung** [comment]
I've emailed you a dataset, thanks for helping out!

**Comment by ankane** [comment]
Thanks for sending, should be fixed in the latest release.
