### ISSUE TITLE
Stack level too deep

### ISSUE THREAD

**Issue by eichert12** [ankane/eps#24]
I'm getting a stack level too deep error in lib/eps/data_frame.rb when trying to train my model.  The  error is occuring at the values_at call on line 121 (https://github.com/ankane/eps/blob/master/lib/eps/data_frame.rb#L121) with the splat (*rows).  The rows size is 130518 so perhaps larger than expected/supported?

      cols.each do |c|
        raise "Undefined column: #{c}" unless columns.include?(c)

        df.columns[c] = columns[c].values_at(*rows)
      end

**Comment by ankane** [comment]
Hey @eichert12, thanks for reporting! Fixed in the commit above.
