### ISSUE TITLE
Gem matrix needed for Ruby version > 3.0

### ISSUE THREAD

**Issue by jfanals** [ankane/eps#25]
I was getting this error when trying to load Rails 7 and Ruby 3.1.2

     `require': cannot load such file -- matrix (LoadError)

As of Ruby 3.1.0 the matrix default gem are now bundled gems.
https://stackoverflow.com/questions/71991514/rails-require-cannot-load-such-file-matrix
https://www.ruby-lang.org/en/news/2021/12/25/ruby-3-1-0-released/

Adding the matrix gem to the `Gemfile` solved the issue.

     gem 'matrix'

**Comment by ankane** [comment]
Hey @jfanals, thanks for reporting! Fixed in the commit above (not sure why I only thought it was needed for Daru). Will push a new release shortly.

**Comment by jfanals** [comment]
That was fast!

Thank you for your amazing gems :)
