### ISSUE TITLE
Memory requirements?

### ISSUE THREAD

**Issue by Deekor** [ankane/eps#27]
I'm new to machine learning and just found this gem.

After reading the readme, it seems memory might be a considerable constraint here. We all know ActiveRecord can get a bit bloated, and if you are training the entirety of a large table, you might run out of memory quickly? You could scale the containers training, but would loading ht PMML file into memory on boot require all containers to be heavy on memory?

Any thoughts or suggestions? Sorry if this is obvious.

**Comment by ankane** [comment]
Hi @Deekor, the memory needed will depend on a number of factors, like the features and algorithm. I'd recommend measuring it for your specific models.
