### ISSUE TITLE
Any data on performance?

### ISSUE THREAD

**Issue by kurko** [ankane/eps#4]
Do you any benchmarks to share? I’m curious how slow it is (I bet it is because Ruby), but I’m mostly curious about the usage of GSL and how much it improves in performance.

**Comment by ankane** [comment]
Hey @kurko,

There's a tiny benchmark method in the Rakefile: https://github.com/ankane/eps/blob/2c83a973da4172efc3617472733360d770b84120/Rakefile#L13

On my machine, GSL runs 10x faster than pure Ruby.

I haven't benchmarked it against other languages and haven't spend much time optimizing performance.

**Comment by kurko** [comment]
👍 thanks.

I'll keep this on the radar and if performance isn't a huge bottleneck, I might try in an upcoming project.
