### ISSUE TITLE
Can't run the detailed example in plain Ruby project

### ISSUE THREAD

**Issue by olimart** [ankane/eps#6]
As always, very good stuff Andrew 👏 

When running the detailed project in plain Ruby file, it breaks at the `save` section because of dependency loading/resolution.
`uninitialized constant Eps::LinearRegression::Nokogiri`

I noticed `Nokogiri` is declared only for dev. environment and don't know if you plan to keep as-is or maybe declare as top-level `::Nokogiri`

**Comment by ankane** [comment]
Thanks @olimart, I've added `require "nokogiri"` to the `to_pmml` method. I've considered making Nokogiri a runtime dependency of the gem, but it's only need for persisting models, so decided against it for now.
