### ISSUE TITLE
Question: number of samples

### ISSUE THREAD

**Issue by olimart** [ankane/eps#7]
I'm getting "Number of samples must be at least two more than number of features"
Can you please describe what 'samples' are?

https://github.com/ankane/eps/blob/ef2291360189ac311a439350efecc361ae788074/lib/eps/linear_regression.rb#L14

```
[
      { bedrooms: 1, bathrooms: 1, price: 100000, city_id: 1, listed_at: Date.new(2018,01,10) },
      { bedrooms: 2, bathrooms: 1, price: 125000, city_id: 2, listed_at: Date.new(2018,02,10) },
      { bedrooms: 2, bathrooms: 2, price: 135000, city_id: 1, listed_at: Date.new(2018,03,10) },
      { bedrooms: 3, bathrooms: 2, price: 162000, city_id: 1, listed_at: Date.new(2018,04,10) },
      { bedrooms: 3, bathrooms: 2, price: 142000, city_id: 2, listed_at: Date.new(2018,02,10) },
      { bedrooms: 2, bathrooms: 2, price: 128000, city_id: 3, listed_at: Date.new(2018,01,10) }
    ]
```

```ruby
def features(house)
  {
    bedrooms: house[:bedrooms],
    city_id: house[:city_id],
    month: house[:listed_at].strftime("%b")
  }
end
```

**Comment by ankane** [comment]
Samples are the number of observations / rows in your model. In the example above, there are 6 samples, and 5 features, which is why you're getting that error. The 5 features are:

- bedrooms
- city_id (you really want to convert this to a categorical feature - i.e. `to_s` - in which case there will be even more features)
- monthJan
- monthFeb
- monthMar

**Comment by olimart** [comment]
Thanks for the clarification.
So I expanded my data set as follows:

```
[
  { bedrooms: 1, bathrooms: 1, price: 100000, city_id: 1, listed_at: Date.new(2018,01,10) },
  { bedrooms: 2, bathrooms: 1, price: 125000, city_id: 2, listed_at: Date.new(2018,02,10) },
  { bedrooms: 2, bathrooms: 2, price: 135000, city_id: 1, listed_at: Date.new(2018,03,10) },
  { bedrooms: 3, bathrooms: 2, price: 162000, city_id: 1, listed_at: Date.new(2018,04,10) },
  { bedrooms: 3, bathrooms: 2, price: 142000, city_id: 2, listed_at: Date.new(2018,02,10) },
  { bedrooms: 2, bathrooms: 2, price: 128000, city_id: 3, listed_at: Date.new(2018,01,10) },
  { bedrooms: 2, bathrooms: 2, price: 122000, city_id: 3, listed_at: Date.new(2018,02,10) },
  { bedrooms: 2, bathrooms: 1, price: 128000, city_id: 3, listed_at: Date.new(2018,01,10) },
  { bedrooms: 1, bathrooms: 1, price: 100500, city_id: 1, listed_at: Date.new(2018,04,10) }
]
```

```
model.predict(bedrooms: 2, bathrooms: 1, city_id: '2')
=> 125500.0
>> model.predict(bedrooms: 2, bathrooms: 1, city_id: '3')
=> 128000.0
```

However, when I query `city_id: 1` I'm expecting price to be between 125k & 128k.
```
>> model.predict(bedrooms: 2, bathrooms: 1, city_id: '1')
=> 128000.0
```

I assume it is because coefficient `city_id1` does not exist (as pointed out in the docs) since

> Categorical features generate coefficients for each distinct value except for one

Which leads to the question, how is the value to remove chosen? (randomly, always the first value...)

**Comment by ankane** [comment]
Eps currently removes the first value that appears in the data, but this ultimately doesn't matter. The model will still make the same predictions no matter which value is removed (except for cases where unseen values are passed).

**Comment by olimart** [comment]
In terms of result, do models perform well with text as well?
My use case (still trying to figure out if I should use such solution) is the following:

As input I want to submit 3 text attributes and I'm expecting the model to predict an associated record.

```ruby
# Event
- source
- error_type
- error_message
- resolution_id

def features(event)
  {
    source: event.source,
    error_type: event.error_type,
    error_message: event.error_message,
    resolution_id: event.resolution_id.to_s,
  }
end

def target(event)
  event.resolution_id
end

$ model.predict(source: 'organic', error_type: 'NotFoundError', error_message: 'Book ABC not found')
=> to return a resolution id
```

Finally, is there a way to regulate attribute importance (weight)?

Obviously I'm missing lot of core knowledge. Thanks for your help.

**Comment by ankane** [comment]
No worries, it's good to hear what questions people have when starting out with machine learning.

A few thoughts on what you're trying to do (which will hopefully answer the questions):

1. The variable you're predicting is categorical (it has a fixed number of values vs making a numeric prediction like housing price), so you'll want to use `event.resolution_id.to_s` to tell Eps to treat it this way. This is known as classification in ML.
2. Eps works with text attributes (referred to as categorical features in the docs), but it does not parse out individual words. For instance, `Book ABC not found` is entirely independent of `Book DEF not found`, despite the fact they have 3 of the same words. This is fine for `source` and `error_type` and may be fine for `error_message` (I'd try it and see how the model performs). You may be able to get better performance by choosing a model that does consider individual words (like https://github.com/jekyll/classifier-reborn).
3. It's the job of the model to figure out the weights.

Let me know if anything needs clarification.

**Comment by ankane** [comment]
Hopefully that made sense.

**Comment by olimart** [comment]
It does. Just need to put things in practice. Thanks again
