### ISSUE TITLE
Using a categorical target raises an exception

### ISSUE THREAD

**Issue by timcraft** [ankane/eps#8]
According to the README it's possible to use a categorical target. I tried this:

```ruby
data = [
  {bedrooms: 1, bathrooms: 1, price: 100000, tag: 'Low'},
  {bedrooms: 2, bathrooms: 1, price: 125000, tag: 'Med'},
  {bedrooms: 2, bathrooms: 2, price: 135000, tag: 'Med'},
  {bedrooms: 3, bathrooms: 2, price: 162000, tag: 'High'}
]
model = Eps::Model.new(data, target: :tag)
puts model.summary
```

That raises `comparison of Array with Array failed (ArgumentError)` from NaiveBayes#_predict. The calculated `probs` array is `[[NaN, "Low"], [NaN, "Med"], [NaN, "High"]]` so presumably choking on those NaN values.

Not sure what the correct fix is—should NaiveBayes#calculate_class_probabilities be changed so that it doesn't return incomparable values? Or am I using it wrong?

**Comment by ankane** [comment]
Hey @timcraft, thanks for reporting 👍 Fixed on master.

**Comment by timcraft** [comment]
@ankane Yes that fixes it, thanks!
